# Generated by Django 5.2.16 on 2026-08-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '쉬움'), (2, '보통'), (3, '어려움')], default=2, verbose_name='난이도')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='분류')),
                ('source', models.CharField(blank=True, help_text='예: 정처기 기출, AI 생성', max_length=100, verbose_name='출처')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='검수 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('term', models.CharField(max_length=100, unique=True, verbose_name='영어 단어')),
                ('meaning', models.CharField(max_length=200, verbose_name='한글 뜻')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('example', models.TextField(blank=True, verbose_name='예문')),
                ('example_translation', models.TextField(blank=True, verbose_name='예문 해석')),
            ],
            options={
                'verbose_name': '단어',
                'verbose_name_plural': '단어',
                'ordering': ['term'],
                'indexes': [models.Index(fields=['is_reviewed', 'term'], name='vocab_word_is_revi_ea9fde_idx')],
            },
        ),
    ]
