# Generated by Django 5.2.16 on 2026-08-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, choices=[('git', '버전 관리(Git)'), ('review', '코드 리뷰(Code Review)'), ('api', 'API'), ('database', '데이터베이스(Database)'), ('devops', '배포·운영(DevOps)'), ('debug', '디버깅(Debugging)')], max_length=50, verbose_name='분류'),
        ),
    ]
