# Generated by Django 5.2.16 on 2026-08-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_alter_word_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='word',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['git', 'review', 'api', 'database', 'devops', 'debug', ''])), name='vocab_word_category_valid'),
        ),
    ]
