# Generated by Django 5.2.16 on 2026-08-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_word_vocab_word_category_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '쉬움'), (2, '보통'), (3, '어려움')], default=2, verbose_name='난이도')),
                ('category', models.CharField(blank=True, choices=[('git', '버전 관리(Git)'), ('review', '코드 리뷰(Code Review)'), ('api', 'API'), ('database', '데이터베이스(Database)'), ('devops', '배포·운영(DevOps)'), ('debug', '디버깅(Debugging)')], max_length=50, verbose_name='분류')),
                ('source', models.CharField(blank=True, help_text='예: 정처기 기출, AI 생성', max_length=100, verbose_name='출처')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='검수 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('text', models.TextField(verbose_name='영어 문장')),
                ('translation', models.TextField(verbose_name='한글 해석')),
                ('kind', models.CharField(choices=[('phrase', '실무 표현'), ('error', '에러 메시지')], default='phrase', max_length=20, verbose_name='종류')),
                ('context', models.CharField(blank=True, max_length=200, verbose_name='나오는 상황')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '문장',
                'verbose_name_plural': '문장',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['is_reviewed', 'id'], name='vocab_sente_is_revi_6fe1fe_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['git', 'review', 'api', 'database', 'devops', 'debug', ''])), name='vocab_sentence_category_valid'), models.CheckConstraint(condition=models.Q(('kind__in', ['phrase', 'error'])), name='vocab_sentence_kind_valid')],
            },
        ),
    ]
