# Generated by Django 5.2.16 on 2026-08-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='slug',
            field=models.CharField(blank=True, max_length=100, verbose_name='시드 키'),
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('slug',), name='vocab_sentence_slug_unique'),
        ),
    ]
