# Generated by Django 5.2.16 on 2026-08-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_sentence_slug_sentence_vocab_sentence_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=100, verbose_name='발음기호'),
        ),
    ]
