# Generated by Django 5.2.16 on 2026-08-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0006_word_pronunciation'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sentence',
            name='vocab_sentence_category_valid',
        ),
        migrations.RemoveConstraint(
            model_name='word',
            name='vocab_word_category_valid',
        ),
        migrations.AlterField(
            model_name='sentence',
            name='category',
            field=models.CharField(blank=True, choices=[('git', '버전 관리(Git)'), ('review', '코드 리뷰(Code Review)'), ('api', 'API'), ('database', '데이터베이스(Database)'), ('devops', '배포·운영(DevOps)'), ('debug', '디버깅(Debugging)'), ('frontend', '프론트엔드(Frontend)'), ('cs', 'CS 기초(Computer Science)')], max_length=50, verbose_name='분류'),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(blank=True, choices=[('git', '버전 관리(Git)'), ('review', '코드 리뷰(Code Review)'), ('api', 'API'), ('database', '데이터베이스(Database)'), ('devops', '배포·운영(DevOps)'), ('debug', '디버깅(Debugging)'), ('frontend', '프론트엔드(Frontend)'), ('cs', 'CS 기초(Computer Science)')], max_length=50, verbose_name='분류'),
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['git', 'review', 'api', 'database', 'devops', 'debug', 'frontend', 'cs', ''])), name='vocab_sentence_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['git', 'review', 'api', 'database', 'devops', 'debug', 'frontend', 'cs', ''])), name='vocab_word_category_valid'),
        ),
    ]
