# Generated by Django 5.2.16 on 2026-08-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_remove_sentence_vocab_sentence_category_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='reading',
            field=models.TextField(blank=True, verbose_name='한글 발음'),
        ),
        migrations.AddField(
            model_name='word',
            name='reading',
            field=models.CharField(blank=True, max_length=120, verbose_name='한글 발음'),
        ),
        migrations.AddField(
            model_name='word',
            name='reading_note',
            field=models.TextField(blank=True, verbose_name='발음 설명'),
        ),
    ]
