# Generated by Django 5.2.16 on 2026-08-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0008_sentence_reading_word_reading_word_reading_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='reading_reviewed',
            field=models.BooleanField(default=False, verbose_name='발음 검수됨'),
        ),
        migrations.AddField(
            model_name='word',
            name='reading_reviewed',
            field=models.BooleanField(default=False, verbose_name='발음 검수됨'),
        ),
    ]
