# Generated by Django 5.2.16 on 2026-09-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_sentence_reading_reviewed_word_reading_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='exam_subject',
            field=models.CharField(blank=True, choices=[('design', '1과목 소프트웨어 설계'), ('develop', '2과목 소프트웨어 개발'), ('database', '3과목 데이터베이스 구축'), ('language', '4과목 프로그래밍 언어 활용'), ('system', '5과목 정보시스템 구축 관리')], help_text='정처기 범위일 때만 채운다. 비워두면 과목 미분류.', max_length=20, verbose_name='정처기 과목'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='is_exam',
            field=models.BooleanField(default=False, help_text='정보처리기사 출제 범위에 드는 항목', verbose_name='정처기 범위'),
        ),
        migrations.AddField(
            model_name='word',
            name='exam_subject',
            field=models.CharField(blank=True, choices=[('design', '1과목 소프트웨어 설계'), ('develop', '2과목 소프트웨어 개발'), ('database', '3과목 데이터베이스 구축'), ('language', '4과목 프로그래밍 언어 활용'), ('system', '5과목 정보시스템 구축 관리')], help_text='정처기 범위일 때만 채운다. 비워두면 과목 미분류.', max_length=20, verbose_name='정처기 과목'),
        ),
        migrations.AddField(
            model_name='word',
            name='is_exam',
            field=models.BooleanField(default=False, help_text='정보처리기사 출제 범위에 드는 항목', verbose_name='정처기 범위'),
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.CheckConstraint(condition=models.Q(('exam_subject__in', ['design', 'develop', 'database', 'language', 'system', ''])), name='vocab_sentence_exam_subject_valid'),
        ),
        migrations.AddConstraint(
            model_name='sentence',
            constraint=models.CheckConstraint(condition=models.Q(('is_exam', True), ('exam_subject', ''), _connector='OR'), name='vocab_sentence_exam_subject_needs_flag'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.CheckConstraint(condition=models.Q(('exam_subject__in', ['design', 'develop', 'database', 'language', 'system', ''])), name='vocab_word_exam_subject_valid'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.CheckConstraint(condition=models.Q(('is_exam', True), ('exam_subject', ''), _connector='OR'), name='vocab_word_exam_subject_needs_flag'),
        ),
    ]
