# Generated by Django 5.2.16 on 2026-09-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0010_sentence_exam_subject_sentence_is_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '쉬움'), (2, '보통'), (3, '어려움')], default=2, verbose_name='난이도')),
                ('category', models.CharField(blank=True, choices=[('git', '버전 관리(Git)'), ('review', '코드 리뷰(Code Review)'), ('api', 'API'), ('database', '데이터베이스(Database)'), ('devops', '배포·운영(DevOps)'), ('debug', '디버깅(Debugging)'), ('frontend', '프론트엔드(Frontend)'), ('cs', 'CS 기초(Computer Science)')], max_length=50, verbose_name='분류')),
                ('source', models.CharField(blank=True, help_text='예: 정처기 기출, AI 생성', max_length=100, verbose_name='출처')),
                ('is_exam', models.BooleanField(default=False, help_text='정보처리기사 출제 범위에 드는 항목', verbose_name='정처기 범위')),
                ('exam_subject', models.CharField(blank=True, choices=[('design', '1과목 소프트웨어 설계'), ('develop', '2과목 소프트웨어 개발'), ('database', '3과목 데이터베이스 구축'), ('language', '4과목 프로그래밍 언어 활용'), ('system', '5과목 정보시스템 구축 관리')], help_text='정처기 범위일 때만 채운다. 비워두면 과목 미분류.', max_length=20, verbose_name='정처기 과목')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='검수 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('text', models.CharField(max_length=120, unique=True, verbose_name='영어 표현')),
                ('scene', models.CharField(blank=True, choices=[('greeting', '인사·소개'), ('shopping', '쇼핑·주문'), ('asking', '묻기·길찾기'), ('trouble', '곤란할 때'), ('smalltalk', '가벼운 대화')], max_length=20, verbose_name='상황')),
                ('pronunciation', models.CharField(max_length=200, verbose_name='발음기호')),
                ('reading', models.CharField(max_length=200, verbose_name='한글 발음')),
                ('meaning', models.CharField(max_length=200, verbose_name='한글 뜻')),
            ],
            options={
                'verbose_name': '일상 표현',
                'verbose_name_plural': '일상 표현',
                'ordering': ['text'],
                'indexes': [models.Index(fields=['is_reviewed', 'text'], name='vocab_daily_is_revi_db0967_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('scene__in', ['greeting', 'shopping', 'asking', 'trouble', 'smalltalk', ''])), name='vocab_dailyphrase_scene_valid'), models.CheckConstraint(condition=models.Q(models.Q(('pronunciation', ''), _negated=True), models.Q(('reading', ''), _negated=True)), name='vocab_dailyphrase_needs_pronunciation'), models.CheckConstraint(condition=models.Q(('is_exam', False), ('exam_subject', '')), name='vocab_dailyphrase_not_exam')],
            },
        ),
    ]
