# Generated by Django 5.2.16 on 2026-08-15 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('free', '자유 문제풀이'), ('daily', '일일공부')], default='free', max_length=10, verbose_name='종류')),
                ('token_id', models.CharField(max_length=64, unique=True, verbose_name='판 식별자')),
                ('started_at', models.DateTimeField(verbose_name='시작')),
                ('finished_at', models.DateTimeField(verbose_name='종료')),
                ('score', models.IntegerField(verbose_name='점수')),
                ('answered', models.PositiveIntegerField(verbose_name='푼 문제')),
                ('correct', models.PositiveIntegerField(verbose_name='맞은 문제')),
                ('skipped', models.PositiveIntegerField(default=0, verbose_name='넘긴 문제')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '문제풀기 기록',
                'verbose_name_plural': '문제풀기 기록',
                'ordering': ['-finished_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20, verbose_name='문제 유형')),
                ('target_type', models.CharField(max_length=10, verbose_name='대상 종류')),
                ('target_id', models.PositiveBigIntegerField(verbose_name='대상 id')),
                ('is_correct', models.BooleanField(verbose_name='맞았나')),
                ('is_skipped', models.BooleanField(default=False, verbose_name='넘겼나')),
                ('elapsed_ms', models.PositiveIntegerField(verbose_name='걸린 시간(ms)')),
                ('score', models.SmallIntegerField(verbose_name='점수')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='learning.quizsession', verbose_name='판')),
            ],
            options={
                'verbose_name': '답',
                'verbose_name_plural': '답',
            },
        ),
        migrations.CreateModel(
            name='DailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='날짜(KST)')),
                ('best_free_score', models.IntegerField(blank=True, default=None, null=True, verbose_name='그날 최고 판 점수')),
                ('daily_study_score', models.IntegerField(default=0, verbose_name='그날 일일공부 점수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '하루 점수',
                'verbose_name_plural': '하루 점수',
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['user', '-day'], name='learning_da_user_id_7fa50e_idx'), models.Index(fields=['day'], name='learning_da_day_d4b8a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='learning_dailyscore_user_day_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['kind', '-score'], name='learning_qu_kind_1fe73c_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsession',
            index=models.Index(fields=['user', '-finished_at'], name='learning_qu_user_id_8a2952_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['session', 'is_correct'], name='learning_qu_session_28d88e_idx'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['target_type', 'target_id'], name='learning_qu_target__ccf2ef_idx'),
        ),
    ]
