# Generated by Django 5.2.16 on 2026-08-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.CharField(max_length=64, verbose_name='판 식별자')),
                ('step', models.PositiveIntegerField(verbose_name='순번')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='만든 때')),
            ],
            options={
                'verbose_name': '판 진행 표시',
                'verbose_name_plural': '판 진행 표시',
                'indexes': [models.Index(fields=['created_at'], name='learning_ro_created_325f50_idx')],
                'constraints': [models.UniqueConstraint(fields=('round_id', 'step'), name='learning_roundstep_round_step_unique')],
            },
        ),
    ]
