# Generated by Django 5.2.16 on 2026-08-18 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_roundstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='날짜(KST)')),
                ('length', models.CharField(choices=[('5m', '5분'), ('10m', '10분'), ('30m', '30분')], max_length=8, verbose_name='길이')),
                ('total_questions', models.PositiveIntegerField(verbose_name='문제 수')),
                ('bonus', models.PositiveIntegerField(default=0, verbose_name='완주 보너스')),
                ('step', models.PositiveIntegerField(default=0, verbose_name='다음 순번')),
                ('answered', models.PositiveIntegerField(default=0, verbose_name='푼 문제 수')),
                ('correct', models.PositiveIntegerField(default=0, verbose_name='맞힌 문제 수')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='끝낸 때')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시작한 때')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_studies', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '일일공부',
                'verbose_name_plural': '일일공부',
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['user', '-day'], name='learning_da_user_id_793407_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='learning_dailystudy_user_day_unique')],
            },
        ),
    ]
