# Generated by Django 5.2.16 on 2026-08-19 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_dailystudy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=10, verbose_name='대상 종류')),
                ('target_id', models.PositiveBigIntegerField(verbose_name='대상 id')),
                ('streak', models.PositiveSmallIntegerField(default=0, verbose_name='연속 정답')),
                ('last_correct_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 정답')),
                ('is_wrong', models.BooleanField(default=False, verbose_name='마지막에 틀렸나')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='만든 때')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='고친 때')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_states', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '복습 상태',
                'verbose_name_plural': '복습 상태',
                'indexes': [models.Index(fields=['user', 'is_wrong', 'last_correct_at'], name='learning_re_user_id_dafabf_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'target_type', 'target_id'), name='learning_reviewstate_user_target_unique')],
            },
        ),
    ]
