# Generated by Django 5.2.16 on 2026-08-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_reviewstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystudy',
            name='question',
            field=models.JSONField(blank=True, null=True, verbose_name='이 순번의 문제'),
        ),
    ]
