# Generated by Django 5.2.16 on 2026-09-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_dailystudy_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystudy',
            name='chunk_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='묶음 수'),
        ),
        migrations.AddField(
            model_name='dailystudy',
            name='chunk_size',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='묶음당 학습 단어'),
        ),
        migrations.AddField(
            model_name='dailystudy',
            name='learned_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='학습한 단어 id'),
        ),
    ]
