# Generated by Django 5.2.16 on 2026-09-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_dailystudy_chunk_count_dailystudy_chunk_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystudy',
            name='issued_chunks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='뽑은 묶음 수'),
        ),
    ]
