# Generated by Django 5.2.16 on 2026-08-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_throttle_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, choices=[('google', '구글 사진'), ('a1', '아바타 1'), ('a2', '아바타 2'), ('a3', '아바타 3'), ('a4', '아바타 4'), ('a5', '아바타 5'), ('a6', '아바타 6')], max_length=10, verbose_name='아바타'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_picture',
            field=models.URLField(blank=True, max_length=500, verbose_name='구글 사진 주소'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='보여지는 이름'),
        ),
    ]
