# Generated by Django 5.2.16 on 2026-09-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_photo',
            field=models.BinaryField(blank=True, null=True, verbose_name='올린 사진'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_photo_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='사진 올린 시각'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_photo_key',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, verbose_name='사진 주소 값'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, choices=[('photo', '올린 사진'), ('google', '구글 사진'), ('a1', '아바타 1'), ('a2', '아바타 2'), ('a3', '아바타 3'), ('a4', '아바타 4'), ('a5', '아바타 5'), ('a6', '아바타 6')], max_length=10, verbose_name='아바타'),
        ),
    ]
